### ISSUE TITLE
Bypass Login

### ISSUE THREAD

**Issue by nranderson** [joshp23/YOURLS-OIDC#3]
Thank you so much for developing this plugin. I currently have it set up and running with my OIDC at auth0.com. Have you put any thought into creating an option to bypass the YOURLS login rather than mapping everyone individually?

It'd be nice if anyone who isn't mapped already, I could specify that they can bypass with a specific role.

**Comment by joshp23** [comment]
Yes! I had the idea to do this in an effort to tightly integrate this with Auth Manager Plus. Since there's some interest I'll probably get to hacking away at it sooner. I don't think that it would be too difficult.

**Comment by joshp23** [comment]
release 0.3.0 has this. :)
